{% set name = "bmi_wrap" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  git_rev: v{{ version }}

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - pyyaml
    - jinja2
    - cookiecutter
    - six
    - scripting

test:
  imports:
    - bmi_wrap
  commands:
    - bmi-wrap -h
    - bmi-render --help

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: https://github.com/csdms/bmi_wrap
  license: MIT
  license_file: LICENSE
  summary: Wrap BMI models with Python bindings.
  dev_url: https://github.com/csdms/bmi_wrap
