package:
  name: bmi_wrap
  version: 0.1.2

source:
  # path: /Users/huttone/git/csdms/bmi_wrap
  # fn: bmi_wrap-0.1.2.tar.gz
  # url: https://github.com/csdms/bmi_wrap/archive/v0.1.2.tar.gz
  git_url: https://github.com/csdms/bmi_wrap
  git_branch: mcflugen/fix-install-issues

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - pyyaml
    - jinja2
    - cookiecutter
    - six
    - scripting

test:
  imports:
    - bmi_wrap
  commands:
    - bmi-wrap -h

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: https://github.com/csdms/bmi_wrap
  license: MIT
  license_file: LICENSE
  summary: Summary of the project
  dev_url: https://github.com/csdms/bmi_wrap
